spring:
  profiles:
    active:
      - dev
  # main:
  #   web-application-type: none

logging:
  level:
    com:
      nexstudio: DEBUG

# ---
# spring:
#   profiles: dev
# nextsudio:
#   username: sfg_dev_user
#   password: guru
#   jbdcURL:  localhost

  
# ---
# spring:
#   profiles: prod
# nextsudio:
#   username: sfg_prod_user
#   password: guru
#   jbdcURL:  localhost
  