INSERT INTO category (description) VALUES ('African');
INSERT INTO category (description) VALUES ('Italian');
INSERT INTO category (description) VALUES ('French');
INSERT INTO category (description) VALUES ('American');
INSERT INTO unit_of_measure (description) VALUES ('Teaspoon');
INSERT INTO unit_of_measure (description) VALUES ('Tablespoon');
INSERT INTO unit_of_measure (description) VALUES ('Cup');
INSERT INTO unit_of_measure (description) VALUES ('Pinch');
INSERT INTO unit_of_measure (description) VALUES ('Millilitre');